### ISSUE TITLE
Testing If Comments Come over - ZenHub

### ISSUE THREAD

**Issue by pjnorton** [pjnorton/buildroot#1]
@pjnorton commented on [Tue Mar 08 2016](https://github.com/pjnorton/mistify-os/issues/1)

To test if comments come over with an issue.  And labels, Milestone, Estimate, Pipeline and Assignee.

---

@pjnorton commented on [Tue Mar 08 2016](https://github.com/pjnorton/mistify-os/issues/1#issuecomment-193931868)

Let's just see what happens

---

@pjnorton commented on [Tue Mar 08 2016](https://github.com/pjnorton/mistify-os/issues/1#issuecomment-193931973)

Y'all.

**Comment by bbickerton** [comment]
Test comment to make Pat happy.

**Comment by pjnorton** [comment]
Pat is now satiated.

**Comment by pjnorton** [comment]
Issue moved to [pjnorton/go-zfs #1](https://github.com/pjnorton/go-zfs/issues/1) via [**ZenHub.io**](https://www.zenhub.io/)
